In [1]:
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin
from pprint import pprint
import pandas as pd

In [2]:
def book_url_to_dict(a: str) -> dict:
    book_page = requests.get(a)
    book_soup = BeautifulSoup(book_page.content, parser = "html.parser")
    book_title = book_soup.find(name = 'h1').get_text()
    book_tr = book_soup.find_all(name = 'tr')
    book_dict = {}
    book_dict['Title'] = book_title
    for i in book_tr:
        book_dict[i.findChild(name = 'th').getText()] = i.findChild(name = 'td').getText()
    return book_dict

In [3]:
def Page_to_book_urls(page: str) -> list:
    HP = requests.get(page)
    soup = BeautifulSoup(HP.content, parser = "html.parser")
    books_comp = soup.find_all(name = 'li', class_='col-xs-6 col-sm-4 col-md-3 col-lg-3')
    return_list = []
    for i in books_comp:
        book_anc = i.findChild(name = "a")
        Extended_url = book_anc.get("href")
        book_url = urljoin(page,Extended_url)
        return_list.append(book_url)
    return return_list

In [5]:
data = []
p = 1
page = f'https://books.toscrape.com/catalogue/page-{p}.html'
while(requests.get(page).status_code==200):
    book_urls = Page_to_book_urls(page)
    for i in book_urls:
        data.append(book_url_to_dict(i))
        #print(book_url_to_dict(i)['Title'])
    p+=1
    print(p)
    page = f'https://books.toscrape.com/catalogue/page-{p}.html'
#print(data)

2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51

In [6]:
SD = pd.DataFrame(data)
SD

,Title,UPC,Product Type,Price (excl. tax),Price (incl. tax),Tax,Availability,Number of reviews
0,A Light in the Attic,a897fe39b1053632,Books,£51.77,£51.77,£0.00,In stock (22 available),0
1,Tipping the Velvet,90fa61229261140a,Books,£53.74,£53.74,£0.00,In stock (20 available),0
2,Soumission,6957f44c3847a760,Books,£50.10,£50.10,£0.00,In stock (20 available),0
3,Sharp Objects,e00eb4fd7b871a48,Books,£47.82,£47.82,£0.00,In stock (20 available),0
4,Sapiens: A Brief History of Humankind,4165285e1663650f,Books,£54.23,£54.23,£0.00,In stock (20 available),0
...,...,...,...,...,...,...,...,...
995,Alice in Wonderland (Alice's Adventures in Won...,cd2a2a70dd5d176d,Books,£55.53,£55.53,£0.00,In stock (1 available),0
996,"Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)",bfd5e1701c862ac3,Books,£57.06,£57.06,£0.00,In stock (1 available),0
997,A Spy's Devotion (The Regency Spies of London #1),19fec36a1dfb4c16,Books,£16.97,£16.97,£0.00,In stock (1 available),0
998,1st to Die (Women's Murder Club #1),f684a82adc49f011,Books,£53.98,£53.98,£0.00,In stock (1 available),0
999,"1,000 Places to See Before You Die",228ba5e7577e1d49,Books,£26.08,£26.08,£0.00,In stock (1 available),0